// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebApi.Database;

namespace TestWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWebApi.Database.Employee", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("AnnualSalary")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Code");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Code = "Emp101",
                            AnnualSalary = 5500.0,
                            DateOfBirth = new DateTime(1988, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Tom"
                        },
                        new
                        {
                            Code = "Emp102",
                            AnnualSalary = 5700.9499999999998,
                            DateOfBirth = new DateTime(1982, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Alex"
                        },
                        new
                        {
                            Code = "Emp103",
                            AnnualSalary = 5900.0,
                            DateOfBirth = new DateTime(1979, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Mike"
                        },
                        new
                        {
                            Code = "Emp104",
                            AnnualSalary = 6500.826,
                            DateOfBirth = new DateTime(1980, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Mary"
                        },
                        new
                        {
                            Code = "Emp105",
                            AnnualSalary = 6700.826,
                            DateOfBirth = new DateTime(1982, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Nancy"
                        },
                        new
                        {
                            Code = "Emp106",
                            AnnualSalary = 7700.4809999999998,
                            DateOfBirth = new DateTime(1979, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Steve"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
